

# Replace with a single Ko-fi username
ko_fi: 'vlastimilnovotny'

# Replace with a single Buy Me a Coffee username
buy_me_a_coffee: 'mxnticek'

# Replace with up to 4 custom sponsorship URLs (comma-separated)
# e.g., ['link1', 'link2']
custom: 'https://paypal.me/mxnticek'

