# Supported funding model platforms

# Replace with up to 4 GitHub Sponsors-enabled usernames (comma-separated)
# e.g., 'user1, user2'
github: ''

# Replace with a single Patreon username
patreon: ''

# Replace with a single Open Collective username
open_collective: ''

# Replace with a single Ko-fi username
ko_fi: 'vlastimilnovotny'

# Replace with a single Tidelift platform-name/package-name
# e.g., 'npm/babel'
tidelift: ''

# Replace with a single Community Bridge project-name
# e.g., 'cloud-foundry'
community_bridge: ''

# Replace with a single Liberapay username
liberapay: ''

# Replace with a single IssueHunt username
issuehunt: ''

# Replace with a single LFX Crowdfunding project-name
# e.g., 'cloud-foundry'
lfx_crowdfunding: ''

# Replace with a single Polar username
polar: ''

# Replace with a single Buy Me a Coffee username
buy_me_a_coffee: ''

# Replace with up to 4 custom sponsorship URLs (comma-separated)
# e.g., ['link1', 'link2']
custom: 'https://paypal.me/mxnticek'

